version: 0.2

phases:
  install:
   commands:
     - echo Entering install phase...
     - echo Nothing to do now          
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - /usr/local/gradle-6.7/bin/gradle build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'build/libs/*.jar'
