server:
  port: 7071

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/cloudxrds
    username: user
    password: user

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
