server:
  port: 80

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/cloudxrds
    username: user
    password: user

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

aws:
  endpoint:
    url: http://localstack:4566
  sns:
    topic-arn: arn:aws:sns:us-east-1:000000000000:CloudX-SNS-uploads-notification-topic
  sqs:
    queue: http://localstack:4566/000000000000/CloudX-SQS-uploads-notification-queue
  s3:
    bucket: cloudx
    region: eu-central-1